# 3. Gradual II model

## 3.1. Allele frequency all parameters for a single replicate

```{r, warning=FALSE, echo=FALSE, message=FALSE}
rm(list = ls())

library(forcats)
library(stringi)
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(patchwork)
library(cowplot)
library(purrr)
library(doParallel)

mythemes <- theme_bw() +
  theme(
    text            = element_text(family = "sans"), 
    legend.position = "none",
    axis.text.x     = element_text(face = "bold", size = 40, angle =25, margin = margin(t = 20), hjust = 1),
    axis.text.y     = element_text(face = "bold", size = 40, angle = 15, margin = margin(r = 10)),
    axis.line       = element_line(size = 3),
    plot.title      = element_text(hjust = 0.01, face = "bold", size = 80, margin = margin(b = 1, unit = "lines")),
    plot.margin     = unit(c(5, 1, 1, 1), "lines"),
    axis.title.x    = element_text(size = 40, face = "bold", margin = margin(t = 30)),
    axis.title.y    = element_text(size = 40, face = "bold", margin = margin(r = 35)),
    strip.text      = element_text(size = 40, face = "bold"),
    panel.spacing   = unit(5, "lines"),
    panel.grid      = element_blank()
  )

source("AlleleFrequencyPlotCode.R")
dirpath <- "../../Output.dir/FourSeasFourAmp.dir/"
pattern <- pattern <- "^genome1_n(10|70|300)(?:\\D|$)"  #"^genome1\\D" 
result <- process_files(dirpath, pattern, "loci")
#
gradIIplots_AF <- result$plots
```

### 3.1.1. Monogenic

```{r, warning=FALSE, fig.height = 15, fig.width = 30, echo=FALSE, message=FALSE}
#| label: GradII_Single_Locus_AllReplicates
#| fig-cap: "SSI 3.1.1. Single locus 30 replicates allele frequency dynamics for gradual four unequal seasons selection model, showing all parameter interactions. The highlighted line indicates the mean allele frequency for each generation."
#| fig-pos: "H"
#| 
#####################################################
######### data processing function ##################
#####################################################

process_files <- function(dirpath, pattern) {
  
  files <- list.files(dirpath, pattern = pattern, full.names = TRUE)
  

  dataframes <- list()
  
  # Extracting parameters
  
  for (file in files) {
    fname <- basename(file) 
    H <- as.numeric(sub(".*_H(0\\.\\d+).*", "\\1", fname))
    loci <- as.numeric( sub(".*_n(\\d+)_.*", "\\1", fname))
    SD <- as.numeric(sub(".*SD(\\d+).*", "\\1", fname))
    replicate <- as.numeric(sub(".*genome(\\d+)_.*", "\\1", fname))
    
    
    data <- read.csv(file, header = TRUE) %>% 
      mutate(
        H         = H,
        loci      = loci,
        SD        = SD,
        replicate = as.factor(replicate))

    dataframes[[fname]] <- data
  }
  
  # Combine all dataframes into one 
  
  combined_data <- bind_rows(dataframes)
  
  return(combined_data)
}

########################################################################
######### Process the files to get combined data and make a plot ######
#######################################################################

dirpath <- "../../Output.dir/FourSeasFourAmp.dir/"
pattern <- "^genome\\d+_n(1)_H0\\.(1|5|8)(SD(1|2|4))?(Gen(10|20|30))?\\.csv$"

combined_data <- process_files(dirpath, pattern)

GradII_SingleLocusAF <- combined_data %>%
  mutate(
    h2_sd = paste0("SD = ", SD, ": ",  "h\u00B2 = ", H)
  ) %>% 
  ggplot(aes(x = Generation, y = Frequency)) +
  geom_line(aes(group = replicate),
            color = "gray50", 
            alpha = 0.8, 
            size = 0.5) +
  stat_summary(fun = mean,
               aes(group = 1), 
               geom = "line", 
               color = "red3", 
               alpha = 1, 
               size = 2) +
  facet_wrap(~ h2_sd, ncol = 3) +
  labs(
    x = "Generation",
    y = "Frequency"
  ) +
  theme_bw() +
  theme(
    text = element_text(family = "sans"),
    legend.position = "none",
    axis.text.x = element_text(face = "bold", size = 40, angle = 35,
                               hjust = 1, margin = margin(t = 10)),
    axis.text.y = element_text(face = "bold", size = 40, angle = 15,
                               margin = margin(r = 10)),
    axis.line   = element_line(size = 2),
    plot.title  = element_text(hjust = 0.01, face = "bold", size = 40),
    axis.title.x = element_text(size = 40, face = "bold",
                                margin = margin(t = 10)),
    axis.title.y = element_text(size = 40, face = "bold",
                                margin = margin(r = 10)),
    strip.text = element_text(size = 40, face = "bold"),
    panel.spacing = unit(5, "lines"),
    panel.grid = element_blank()
  )

GradII_SingleLocusAF
```

### 3.1.2. Oligogenic

```{r, fig.height = 15, fig.width = 30, echo=FALSE}
#| label: GradII_Olig_AF
#| fig-cap: "SI 3.1.2. Allele frequency dynamics for all parameter combinations from a single replicate, gradual four unequal seasons selection model. Each line  represents the frequency trajectory for a locus from oligogenic trait (10 loci)."
#| fig-pos: "H"

GradII_Olig_AF <- gradIIplots_AF[[10]] +
  ggtitle("Gradual II Oligogenic") +
  theme(
    plot.title = element_text(
      hjust = 0.5,         
      size = 70, 
      color = "firebrick4",
      margin = margin(b = 40) 
    )
  )

print(GradII_Olig_AF)
```

### 3.1.3. Polygenic 70 loci

```{r, fig.height = 15, fig.width = 30, echo=FALSE}
#| label: GradII_Poly_70_AF
#| fig-cap: "SI 3.1.3. Allele frequency dynamics for all parameter combinations from a single replicate, gradual four unequal seasons selection model. Each line  represents the frequency trajectory for a locus from polygenic trait (70 loci)."
#| fig-pos: "H"

GradII_Poly_70_AF <- gradIIplots_AF[[70]] +
  ggtitle("Gradual II Poligenic (70 loci)") +
  theme(
    plot.title = element_text(
      hjust = 0.5,         
      size = 70, 
      color = "firebrick4",
      margin = margin(b = 40) 
    )
  )

print(GradII_Poly_70_AF)
```

### 3.1.4. Polygenic 300 loci

```{r, fig.height = 15, fig.width = 30, echo=FALSE}
#| label: GradII_Poly_300_AF
#| fig-cap: "SI 3.1.4. Allele frequency dynamics for all parameter combinations from a single replicate, gradual four unequal seasons selection model. Each line  represents the frequency trajectory for a locus from polygenic trait (300 loci)."
#| fig-pos: "H"

GradII_Poly_300_AF <- gradIIplots_AF[[300]] +
  ggtitle("Gradual II Poligenic (300 loci)") +
  theme(
    plot.title = element_text(
      hjust = 0.5,         
      size = 70, 
      color = "firebrick4",
      margin = margin(b = 40) 
    )
  )

print(GradII_Poly_300_AF)
```

## 3.2. Spectral analysis for all parameters

```{r, echo=FALSE}
run_fft_analysis <- function(folder_path, pattern, spectrum_span = 2) {
  library(parallel)
  library(doParallel)
  library(foreach)
  library(dplyr)
  library(ggplot2)
  library(cowplot)
  
  
  theme_set(theme_classic())
  
  mythemes <- theme_bw() +
    theme(
      text            = element_text(family = "sans"), 
      legend.position = "none",
      axis.text.x     = element_text(face = "bold", size = 40, angle = 25, 
                                       margin = margin(t = 20), hjust = 1),
      axis.text.y     = element_text(face = "bold", size = 40, angle = 15, 
                                       margin = margin(r = 10)),
      axis.line       = element_line(size = 3),
      plot.title      = element_text(hjust = 0.01, face = "bold", size = 80, 
                                       margin = margin(b = 1, unit = "lines")),
      plot.margin     = unit(c(5, 1, 1, 1), "lines"),
      axis.title.x    = element_text(size = 40, face = "bold", margin = margin(t = 30)),
      axis.title.y    = element_text(size = 40, face = "bold", margin = margin(r = 35)),
      strip.text      = element_text(size = 40, face = "bold"),
      panel.spacing   = unit(5, "lines"),
      panel.grid      = element_blank()
    )
  
  # File list
  
  file_list <- list.files(path = folder_path, pattern = pattern, full.names = TRUE)
  
  if (length(file_list) == 0) {
    stop("No files found with the given pattern.")
  }
  
  # Create a data frame with filenames and extract parameters
  
  files_df <- data.frame(file_name = file_list) %>%
    mutate(
      base_name = basename(file_name),  
      n = ifelse(
         grepl("_n\\d+", base_name),
         as.numeric(sub(".*_n(\\d+).*", "\\1", base_name)),
         NA_real_
           ),
      replct <- as.numeric(sub(".*genome(\\d+)_.*", "\\1", base_name)),
      H = ifelse(
         grepl("_H[0-9]+\\.?[0-9]*", base_name),
         as.numeric(sub(".*_H([0-9]+\\.?[0-9]*).*", "\\1", base_name)),
         NA_real_
        ),
      SD = ifelse(
        grepl("SD[0-9]+(\\.[0-9]+)?", base_name),
        as.numeric(sub(".*SD([0-9]+(?:\\.[0-9]+)?).*", "\\1", base_name)),
        NA_real_
        ),
      Gen = ifelse(
        grepl("Gen\\d+", base_name),
        as.numeric(sub(".*Gen(\\d+).*", "\\1", base_name)),
        NA_real_
        ),
      Genome = case_when(
        n == "1" ~ "Monogenic",
        n == "10" ~ "Oligogenic",
        n == "70" ~ "Polygenic 70",
        n == "100" ~ "Polygenic 100",
        n == "300" ~ "Polygenic 300",
        TRUE ~ "Unknown"
      )
    ) %>%
    mutate(
      n = as.numeric(n),
      H = as.numeric(H),
      SD = as.numeric(SD),
      Gen = as.numeric(Gen),
      param_combination = paste0("n_", n, "_H", H, 
                                 ifelse(!is.na(SD), paste0("_SD", SD), ""), 
                                 ifelse(!is.na(Gen), paste0("_Gen", Gen), ""))
    )
  
  # Set up parallel backend
  
  num_cores <- detectCores()
  cl <- makeCluster(64)
  registerDoParallel(cl)
  
  # Read and combine data from all replicate files in parallel
  combined_data_list <- foreach(i = seq_along(files_df$file_name), .packages = c("dplyr")) %dopar% {
    file <- files_df$file_name[i]
    params <- files_df[i, ]
    df <- read.csv(file)
    data <- df %>%
      mutate(
        allele_id = as.factor(Position),
        generation = as.numeric(Generation),
        allele_frequency = Frequency,
        file = params$base_name,
        replct = params$replct,
        n = params$n,
        H = params$H,
        SD = params$SD,
        Gen = params$Gen,
        Genome = params$Genome,
        param_combination = params$param_combination
      ) %>%
      dplyr::select(allele_id, generation, allele_frequency, replct, n, H, SD, Gen, Genome, param_combination)
    data
  }
  combined_data <- bind_rows(combined_data_list) %>% filter(generation <=1802)

  filtered_data <- combined_data 
  
  # Calculating the mean allele frequency for each grouping
  mean_allele_data <- filtered_data %>%
    group_by(generation, n, replct, H, SD, Gen, Genome, param_combination) %>%
    summarize(mean_allele_frequency = mean(allele_frequency), .groups = "drop")
  
  # Creating time series objects
  ts_data_list <- mean_allele_data %>%
    group_by(n, replct, H, SD, Gen, Genome, param_combination) %>%
    summarize(ts_data = list(ts(mean_allele_frequency, start = min(generation), frequency = 1)), .groups = 'drop')
  
  # Computing spectral density estimates in parallel
  spec_results_list <- foreach(i = 1:nrow(ts_data_list), .packages = c("stats")) %dopar% {
    ts_data <- ts_data_list$ts_data[[i]]
    spectrum(ts_data, spans = spectrum_span, plot = FALSE)
  }
  
  # Preparing data for plotting
  plot_data_list <- foreach(i = seq_along(spec_results_list), .packages = c("dplyr")) %dopar% {
    spec_result <- spec_results_list[[i]]
    params <- ts_data_list[i, ]
    period <- 1 / spec_result$freq
    data.frame(
      Period = period,
      Spectrum = spec_result$spec,
      n = params$n,
      replct = params$replct,
      H = params$H,
      SD = params$SD,
      Gen = params$Gen,
      Genome = params$Genome,
      param_combination = params$param_combination
    )
  }
  
  stopCluster(cl)
  

  plot_data <- bind_rows(plot_data_list)
  

  plot_data <- plot_data %>%
    group_by(param_combination) %>%
    mutate(threshold = case_when(
      Gen == 10 ~ 40,
      Gen == 20 ~ 50,
      Gen == 30 ~ 80,
      TRUE ~ 80
    )) %>%
    filter(Period < threshold) %>%
    ungroup() %>%
    mutate(
      Genome_Gen = paste0("Genome = ", Genome, " Gen = ", Gen),
      h2_sd = paste("H = ", H," ", "SD = ", SD, sep = ""),
      #H_label = paste0("H = ", H),
      #SD_label = ifelse(!is.na(SD), paste0("SD = ", SD), "No SD"),
      Gen_label = ifelse(!is.na(Gen), paste0("Gen = ", Gen), "No Gen"),
      n_label = paste0("n_", n)
    )
  
  fft_plots <- list()
  
  uni_genomegen <- unique(plot_data$Genome_Gen)
  
  for(genomegen in uni_genomegen){
    myplot_data <- plot_data %>% filter(Genome_Gen == genomegen)

  fft_plots[[genomegen]] <- ggplot(myplot_data, aes(x = Period, y = Spectrum, color = factor(replct), group = factor(replct))) +
    geom_line(size = 1.1) +
    facet_wrap( ~ h2_sd, scales = "free") +
    labs(x = "Period (Generations)", y = "Spectral Density") +
    mythemes
  }
  
  return(fft_plots)
}

```

```{r, fig.height = 8, fig.width = 12, echo=FALSE}
dirpath <- "../../Output.dir/FourSeasFourAmp.dir/"
pattern <- "^genome"
result <- run_fft_analysis(dirpath, pattern, spectrum_span = 2)
```

### 3.2.1. Polygenic 70

```{r, fig.height = 15, fig.width = 35, echo=FALSE}
#| label: GradII_Poly_70_SA
#| fig-cap: "SI 3.2.1. Spectral density across 30 replicates for polygenic trait (70 loci) with gradual four unequal seasons selection model, all parameter combinations. For high parameters, ach peak  represents one of the four full cycle of selection periods while the peaks are murky under low heritability and selection pressure (first column)."
#| fig-pos: "H"

GradII_Poly_70_SA <- result[[3]] +
  ggtitle("Spectral Density: Gradual II Polygenic (70 loci)") +
  theme(
    plot.title = element_text(
      hjust = 0.5,         
      size = 70, 
      color = "firebrick4",
      margin = margin(b = 40) 
    )
  )

print(GradII_Poly_70_SA)
```

### 3.2.2. Polygenic 300

```{r, fig.height = 15, fig.width = 35, echo=FALSE}
#| label: GradII_GradII_Poly_300_SA
#| fig-cap: "SI 3.2.2. Spectral density across 30 replicates for polygenic trait (300 loci) with gradual four unequal seasons selection model, all parameter combinations. For high parameters, ach peak  represents one of the four full cycle of selection periods while the peaks are murky under low heritability and selection pressure (first column)."
#| fig-pos: "H"
GradII_GradII_Poly_300_SA <- result[[5]] +
  ggtitle("Spectral Density: Gradual II Polygenic (300 loci)") +
  theme(
    plot.title = element_text(
      hjust = 0.5,         
      size = 70, 
      color = "firebrick4",
      margin = margin(b = 40) 
    )
  )

print(GradII_GradII_Poly_300_SA)
```

# 

## 
