---
title: "Predicting phenotypic and genotypic evolution given fluctuating selection"
author: "Esdras T"
format: 
  revealjs:
    standalone: true
    self-contained: true
    slide-number: true
    show-slide-number: all
editor: visual
---

## Aims

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(stringr)
library(cowplot)
theme_set(theme_cowplot())
```

```{r, echo=FALSE, message=FALSE}
mytheme <- function(){
  theme_set(theme_cowplot())+
    theme(axis.title = element_text(face = "bold"),
          axis.text = element_text(face = "italic"),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none")
}
```

## Genotype file

```{r, echo=FALSE}
mygeno <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS_30repl.dir/genome1_n100_H0.5SD3Gen30.csv") %>% dplyr::select(-Origin)
knitr::kable(head(mygeno))
```

## Phenotype file

```{r, echo=FALSE}
mypheno <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS_30repl.dir//MeanPhenotypes1_n100_H0.5SD3Gen30.csv")
knitr::kable(head(mypheno))
```

## Allele Frequency (single plot FS)

```{r , fig.width=8, fig.height=6, echo=FALSE}
mygeno %>% ggplot(aes(Generation, Frequency, color = as.character(Position)))+
  geom_line(linewidth = 0.2)+
  ggtitle("Alle freq plot h2 = 0.5, sd = 3 for 30 Generations")+
  mytheme()
```

## Allele Frequency (single model)

```{r, fig.width=8, fig.height=6, echo=FALSE}
source("~/YeastProj.dir/evogen-sims/ET_Yeast/Code/Selection_Models/WF.dir/Plotting/PrelimVisualSelect.R")
dir_path <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS_30repl.dir/MultiLinFS_30repl.dir/"
pattern <- "^genome.*0\\.5SD3Gen30\\.csv$"
ncol <- 3

plot_files(dir_path, pattern, ncol = ncol)
```

## Mean Allele Frequency (all variables)

```{r, fig.width=8, fig.height=6, echo=FALSE, message=FALSE}
source("~/YeastProj.dir/evogen-sims/ET_Yeast/Code/Selection_Models/WF.dir/Plotting/MultiLinFS_30repl.dir/MultiLinFSCode.R")
dir_path <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS_30repl.dir/MultiLinFS_30repl.dir/"
pattern <- "^genome\\d+_n\\d+_H0[.0-9]+SD\\d+Gen\\d+\\.csv$"
output_dir <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/Plots.dir/LinFS_30repl.dir/"
allele_feq_fx(dir_path, pattern, output_dir)
```

## Phenotypes (single plot FS)

```{r, fig.width=8, fig.height=6, echo=FALSE}
mypheno %>% ggplot(aes(Generation, Phenotype))+
  geom_line(linewidth = 0.2)+
  ggtitle("Phenotype plot h2 = 0.5, sd = 3 for 30 Generations")+
  mytheme()
```

## Phenotypes (single model)

```{r, fig.width=8, fig.height=6, echo=FALSE, message=FALSE}
source("~/YeastProj.dir/evogen-sims/ET_Yeast/Code/Selection_Models/WF.dir/Plotting/PrelimVisualSelect.R")
dir_path <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS_30.dir/MultiLinFS_30.dir/"
pattern <- "^MeanPhenotypes\\d+_n\\d+_H0[.0-9]+SD\\d+Gen\\d+\\.csv$"
ncol <- 3

Pheno_files(dir_path, pattern, ncol)
```

## Phenotypes (all variables)

```{r, fig.width=8, fig.height=6, echo=FALSE, message=FALSE}
source("~/YeastProj.dir/evogen-sims/ET_Yeast/Code/Selection_Models/WF.dir/Plotting/MultiLinFS_30.dir/MultiLinFSCode.R") 
dir_path <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS_30.dir/MultiLinFS_30.dir/" 
pattern <- "^MeanPhenotypes\d+_n100+_H0[.5]+SD\d+Gen\d+\.csv$" 
output_dir <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/Plots.dir/LinFS_30.dir/MultiLinFS_30.dir/Phenotypes/" 
pheno_fx(dir_path, pattern, output_dir)
```
