---
title: "Shiny_plots"
author: "Ezra Tuyishimre"
format: html
server: shiny
---

```{r}
#| echo: false
library(tidyverse)
library(cowplot)
```

```{r}
#| echo: false
source("/home/etb68/YeastProj.dir/evogen-sims/ET_Yeast/Code/Plotting/reuse_for_plots.V3.R")
```

```{r}
#| echo: false
mypath <- "/home/etb68/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Select_Press/ConstFluctSelect.dir/Plots.dir/Optim_Plot.dir/GenoPlot.dir"

mygenomefiles <- list.files(path = "/home/etb68/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Select_Press/ConstFluctSelect.dir/Selection_Optim.dir/", pattern = "^genome.*\\.csv$", full.names = TRUE)

for (mygenomefile in mygenomefiles) {
  df <- read.csv(mygenomefile)
  my_plots(df, mygenomefile, mypath)
}
```

```{r}
#| echo: false
myphenofiles <- list.files(path = "/home/etb68/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Select_Press/ConstFluctSelect.dir/Selection_Optim.dir/", pattern = "^MeanPhenotypes.*\\.csv$", full.names = TRUE)

for (myphenofile in myphenofiles) {
  df <- read.csv(myphenofile)
  mon_plots(df, myphenofile, mypath)
}
```

```{r}
#| echo: false
files <- list.files(path = "/home/etb68/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Select_Press/ConstFluctSelect.dir/Selection_OptimGen.dir/", pattern = "^genome.*SD2\\.csv$", full.names = TRUE)

all_results <- process_files(files)

fft1 <- all_results %>%
  mutate(Frequency = 1/Frequency) %>%
  filter(Frequency < 40) %>%
  ggplot(aes(Frequency, spec, color = File)) +
  geom_line(linewidth = 1.1) +
  theme(legend.position = "none") +
  xlab("Periodicity") +
  ylab("Spectral Density")

fft1
```
