---
title: "BioLunch"
author: "ET"
format: html
editor: visual
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(stringr)
library(cowplot)
theme_set(theme_cowplot())
```

```{r, echo=FALSE, message=FALSE}
mytheme <- function(){
  theme_set(theme_cowplot())+
    theme(axis.title = element_text(face = "bold"),
          axis.text = element_text(face = "italic", size = 12),
          axis.line = element_line(size = 1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none")
}
```

```{r, fig.width=12, fig.height=8, echo=FALSE}
Generation <- seq(1, 100)
Optimum <- seq(90, 110, length.out = 100)
df <- data.frame(Generation, Optimum)

p1 <- ggplot(df) + 
  geom_blank(aes(Generation, Optimum)) +
  geom_hline(yintercept = 100, color = "darkred", size = 2)+
  annotate("text", x = 50, y = 100, 
           label = "Mean Phenotype", 
           size = 12, vjust = -1.5, col = "darkred")+
  geom_hline(yintercept = 105, size = 2)+
annotate("text", x = 50, y = 105, label = "Optium", size = 12, vjust = -1.5, col = "black")+
  labs(x = NULL, y = NULL)+
  mytheme()

p1

```

```{r}
Generation <- seq(1, 100)
Optimum <- seq(90, 110, length.out = 100)
df <- data.frame(Generation, Optimum)

p1 <- ggplot(df) + 
  geom_blank(aes(Generation, Optimum)) +
  geom_hline(yintercept = 100, color = "darkred", size = 1) +
  annotate("text", x = 50, y = 100, 
           label = "Mean Phenotype", 
           size = 3, vjust = 1.5, col = "darkred") +
  geom_hline(yintercept = 105, size = 1) +
 # annotate("text", x = 50, y = 105, label = "Optimum", 
  #         size = 3, vjust = -1.5, col = "black") +
  labs(x = NULL, y = NULL) + 
  theme(axis.text = element_text(size = 12),
        axis.line = element_line(size = 1)) 

p1

```

```{r}
Opti_Gen <- tibble(Generation = seq(1:100),
                   Optimum = rep(c(rep(110, 10), rep(90, 10)), 5))

mu_pheno = mean(Opti_Gen$Optimum)

Opt_Data <- Opti_Gen %>% 
  filter(Generation == 0 | Generation %% 25 != 0)

p2 <- Opt_Data %>% 
  ggplot(aes(x = Generation, y = Optimum))+
  geom_line(size = 1)+
  geom_hline(yintercept = mu_pheno, col = "darkred", size = 1)+
  annotate("text", x = 50, y = mu_pheno, 
           label = "Mean Phenotype", 
           size = 3, vjust = -8, hjust = - 0.1, 
           col = "darkred", angle = 85)+
  labs(x = NULL, y = NULL)+ 
  theme(axis.text = element_text(size = 12),
        axis.line = element_line(size = 1)) 

p2

```

```{r}
Generation <- seq(1, 100, length.out = 400) 
Optimum <- 100 + 10 *sin(2 * pi* Generation / 25) 
df <- data.frame(Generation, Optimum) 

p3 <- ggplot(df) + 
  geom_line(aes(Generation, Optimum), size = 1) + 
  geom_hline(yintercept = mean(Optimum), 
             color = "darkred", size = 1)+ 
  annotate("text", x = 50, y = 100, 
           label = "Mean Phenotype", 
           size = 3, vjust = -3, hjust = - 0.1, 
           col = "darkred", angle = 80)+ 
  labs( x = NULL, y = NULL)+
  theme(axis.text = element_text(size = 12),
        axis.line = element_line(size = 1))

p3

```

```{r}
Generation <- seq(1, 100, length.out = 400)

Optimum <- 100 + 10 * sin(2 * pi * Generation / 25) + 2 * sin(2 * pi * Generation / 10) + 5 * sin(2 * pi * Generation / 5) + 1 * sin(2 * pi * Generation / 2)

df <- data.frame(Generation, Optimum)

p4 <- ggplot(df) + 
  geom_line(aes(Generation, Optimum), size =1) +
  geom_hline(yintercept = mean(Optimum), 
             color = "darkred", size = 1)+
  annotate("text", x = 50, y = 100, 
           label = "Mean Phenotype", 
           size = 3, vjust = -3, hjust = - 0.1,
           col = "darkred", angle = 80)+ 
  labs( x = NULL, y = NULL)+
  theme(axis.text = element_text(size = 12, angle = 45),
        axis.line = element_line(size = 1))

p4
```

```{r}
mygrid <- plot_grid(p1, p2, p3, p4, labels = "AUTO", label_size = 10,label_colour = NULL, label_x = 0.15, label_y = 1.02, hjust = -0.5, vjust = 1.5, scale = 1,ncol = 2, align = "hv") +
  theme(plot.margin = margin(t = 10, r = 10, b = 10, l = 10)) +
  draw_label("Generation", size = 12, x = 0.5, y = -0.0105, hjust = .3, fontface = "bold")+
  draw_label("Phenotype", size = 12, x = -0.01, y = 0.5, vjust = 0.5, angle = 90, fontface = "bold")

mygrid
```
