---
title: "CS_FFT"
author: "Esdras T."
format: html
editor: visual
---

```{r}
library(tidyverse)
library(MASS)
library(pracma)
library(cowplot)
library(ggforce)
library(future)
library(furrr)
library(purrr)
library(caret)
library(here)
library(patchwork)
theme_set(theme_cowplot())
```

### Using Spectrum function in R

```{r}
file <- read.csv("/home/etb68/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Select_Press/ConstFluctSelect.dir/FS.dir/genome4_100_H0.5SD4Gen10.csv") %>% dplyr::select(!c(Origin, Effect))

dat_wide <- pivot_wider(file[,c("Generation","Position","Frequency")], names_from=Position, values_from=Frequency)
dat_wide[is.na(dat_wide)] <- 0 
ff1 <-dat_wide[,2:101]
ttest <- spectrum(ff1, spans=2, plot=FALSE)
out.spect <- rowMeans(ttest$spec)
ddifs <- diff(as.matrix(ff1), lag=1)
out.abs.diff1 <- rowMeans(abs(ddifs))

dd <- data.frame("Frequency"= rep((ttest$freq)), 
                 "sel"=rep("CS",each=1000),
                 "spec"=out.spect)
dd %>% 
  ggplot(aes(Frequency, spec)) +
  geom_line(size=1.1) +
  #geom_vline(xintercept = 20, color= 'grey30') +
  scale_color_manual(values=c("coral","grey30","steelblue")) +
  xlab("Periodicity (Generations)") +
  ylab("Spectral Density") +
  facet_zoom(xlim = c(0.03,0.07),ylim = c(0, 0.005))
             #+
  #annotate("text",label="simulated \ndatasets", x=15, y =0.012)

dd1 <- data.frame("Frequency"= rep(1/(ttest$freq)), 
                 "sel"=rep("CS",each=1000),
                 "spec"=out.spect)
simp <- dd1 %>% filter(Frequency <= 40) %>%
  ggplot(aes(Frequency, spec)) +
  geom_line(size=1.1) +
  geom_vline(xintercept = 20, color= 'coral') +
  scale_color_manual(values=c("coral","grey30","steelblue")) +
  xlab("Periodicity") +
  ylab("Spectral Density")

simp

```

#### What about all files?

```{r}

files <- list.files(path = "/home/etb68/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Select_Press/ConstFluctSelect.dir/CS.dir/", pattern = "^genome.*30\\.csv$", full.names = TRUE)

all_results <- data.frame()

#Iterate files in the directory
for (file_name in files) {
  #read in each file
  file <- read.csv(file_name) %>% dplyr::select(!c(Origin, Effect))
  
  # Pivot wider your data to tranform for each generation
  dat_wide <- pivot_wider(file[,c("Generation","Position","Frequency")], names_from=Position, values_from=Frequency)
  dat_wide[is.na(dat_wide)] <- 0 
  ff1 <-dat_wide[,2:101]
  
  # Apply spectrum and calculate row means
  ttest <- spectrum(ff1, spans=2, plot=FALSE)
  out.spect <- rowMeans(ttest$spec)
  
  # Prepare data frame for plot
  dd <- data.frame("Frequency"= rep((1/ttest$freq)), 
                   "File"= basename(file_name), # Add a column for file name for color
                   "sel"=rep("CS",each=1000),
                   "spec"=out.spect)
  
  # Combine with previous results
  all_results <- rbind(all_results, dd)
}
```

```{r}

# Filter and plot the results
 fft1 <- all_results %>%
  filter(Frequency <= 100) %>%
  ggplot(aes(Frequency, spec, color = File)) +  # Add color = File to aes function
  geom_line(size=1.1) +
  theme(legend.position = "none")+
  xlab("Periodicity") +
  ylab("Spectral Density")
 
  my_fft <- file.path("/home/etb68/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Select_Press/ConstFluctSelect.dir/Plots.dir/CS_Plot.dir/FFT.dir", "SD30_FFT.png")
  png(filename = my_fft, width = 6, height = 4, units = "in", res = 300)
  print(fft1)
  dev.off()
```
