---
title: "Phenotype plots"
format: html
author: "Esdras T"
editor: visual
---

## Source code

```{r, message=FALSE}
rm(list = ls())
source("~/YeastProj.dir/evogen-sims/ET_Yeast/Writing1.dir/Code.dir/AlleleFrequencyPlotCode.R")
```

### Neutral selection

```{r}
dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/NS.dir/"
pattern <-  "^genome(1|2|3)_n\\d+_H0.1_*" # "^genome15\\D" #(\\D|$)
result <- process_files(dirpath, pattern, "loci_gen")
combined_data <- result$combined_data
plots <- result$plots
plots
```

### Constant Selection

```{r}
dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/CS.dir/"
pattern <- "^genome(1|2|3)_n\\d+_H*" #"^genome1\\D" #(\\D|$)
result <- process_files(dirpath, pattern, "loci_gen")
combined_data <- result$combined_data
plots <- result$plots
plots
```

### Linear Fluctuating

```{r}
dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/"
pattern <- "^genome15_n\\d+_H0.1_*" #(\\D|$)
result <- process_files(dirpath, pattern, "loci_gen")
combined_data <- result$combined_data
plots <- result$plots
plots
```

### Sinusoidal I

```{r}
dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFS.dir/"
pattern <- "^genome15\\D" #(\\D|$)
result <- process_files(dirpath, pattern, "loci_gen")
combined_data <- result$combined_data
plots <- result$plots
plots
```

### Sinusoidal II

```{r}
dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFSGen.dir/" 
pattern <- "^genome15\\D" #(\D|$) 
result <- process_files(dirpath, pattern, "loci_gen") 
combined_data <- result$combined_data 
plots <- result$plots 
plots
```
