---
title: "Optimum_Illustration"
author: "Esdras T"
format: html
editor: visual
---

## Optimum Illustration

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(cowplot)
library(purrr)
library(doParallel)
theme_set(theme_cowplot())
```

```{r, echo=FALSE, message=FALSE}
mytheme <- function(){
  theme_set(theme_cowplot())+
    theme(axis.title = element_text(face = "plain"),
          axis.text = element_text(face = "plain"),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none")
}
```

### Constant Selection

```{r, echo=FALSE}
Generation <- seq(1, 100)
Optimum <- seq(90, 110, length.out = 100)
df <- data.frame(Generation, Optimum)

p1 <- ggplot(df) + 
  geom_blank(aes(Generation, Optimum)) +
  geom_hline(yintercept = 100, color = "darkred")+
  annotate("text", x = 50, y = 100, label = "Mean Phenotype", size = 3, vjust = -1.5, col = "darkred")+
  geom_hline(yintercept = 105)+
annotate("text", x = 50, y = 105, label = "Optium", size = 3, vjust = -1.5, col = "black")+
  labs(x = NULL, y = NULL)+ # title = "Constant Optimum", 
  mytheme()

p1
```

### Fluctuating linear

```{r, echo=FALSE}

Opti_Gen <- tibble(Generation = seq(1:100),
                   Optimum = rep(c(rep(110, 10), rep(90, 10)), 5))

mu_pheno = mean(Opti_Gen$Optimum)

Opt_Data <- Opti_Gen %>% 
  filter(Generation == 0 | Generation %% 10 == 0)

p2 <- Opt_Data %>% 
  ggplot(aes(x = Generation, y = Optimum))+
  geom_line()+
  geom_hline(yintercept = mu_pheno, col = "darkred")+
  annotate("text", x = 50, y = mu_pheno, label = "Mean Phenotype", size = 3, vjust = -1.5, col = "darkred")+
  #annotate("text", x = 55, y = 116, label = "Optimum", size = 3, vjust = -1.5, col = "black")+
  labs(x = NULL, y = NULL)+ # title = "Fluctuating Linear Opimum", 
  mytheme()

p2
```

### Sinusoidal I

```{r, echo=FALSE}
Generation <- seq(1, 100, length.out = 400) 
Optimum <- 100 + 10 *sin(2 * pi* Generation / 25) 
#noise <- rnorm(length(Optimum), c(seq(1:5)), c(seq(10:20)))
#Optimum <- Optimum + noise
df <- data.frame(Generation, Optimum) 

p3 <- ggplot(df) + 
  geom_line(aes(Generation, Optimum)) + 
  geom_hline(yintercept = mean(Optimum), color = "darkred")+ 
  annotate("text", x = 50, y = 100, label = "Mean Phenotype", size = 3, vjust = -1.5, col = "darkred")+ 
  #annotate("text", x = 42, y = 122, label = "Optimum", size = 3, vjust = -1.5, col = "black")+
  labs( x = NULL, y = NULL)+ # title = "Sinusoidal I Period",
  mytheme()

p3
```

### Sinusoidal II

```{r, echo=FALSE}
Generation <- seq(1, 100, length.out = 400)
#Optimum <- 100 + 10 * sin(2 * pi * Generation / 25) + 2 * sin(2 * pi * Generation / 10) + 0.5 * sin(2 * pi * Generation / 5) + 1 * sin(2 * pi * Generation / 2)

Optimum <- 100 + 10 * sin(2 * pi * Generation / 25) + 2 * sin(2 * pi * Generation / 10) + 5 * sin(2 * pi * Generation / 5) + 1 * sin(2 * pi * Generation / 2)

# Optimum <- 100 + 10 * sin(2 * pi * Generation / 25) + 10 * sin(2 * pi * Generation / 10) + 10 * sin(2 * pi * Generation / 5) + 10 * sin(2 * pi * Generation / 2)
# Optimum/4

df <- data.frame(Generation, Optimum)

p4 <- ggplot(df) + 
  geom_line(aes(Generation, Optimum)) +
  geom_hline(yintercept = mean(Phenotype), color = "darkred")+
  annotate("text", x = 50, y = 100, label = "Mean Phenotype", size = 3, vjust = -1.5, col = "darkred")+
  #annotate("text", x = 38, y = 105, label = "Optimum", size = 3, vjust = -1.5, col = "black")+
  labs(x = NULL, y = NULL)+ #title = "Sinusoidal IV Periods",
  mytheme()

p4
```

### All plots together

```{r, echo=FALSE, message=FALSE}
# library(patchwork)
# (p1+p2)/(p3+p4)
```

```{r, echo=FALSE}

 mygrid <- plot_grid(p1, p2, p3, p4, labels = "AUTO", label_size = 10,label_colour = NULL, label_x = 0.15, label_y = 1.02, hjust = -0.5, vjust = 1.5, scale = 1,ncol = 2, align = "hv") +
  theme(plot.margin = margin(t = 10, r = 10, b = 10, l = 10)) +
  draw_label("Generation", size = 12, x = 0.5, y = -0.0105, hjust = .3, fontface = "bold")+
  draw_label("Optimum", size = 12, x = -0.01, y = 0.5, vjust = 0.5, angle = 90, fontface = "bold")
 mygrid

```

```{r, echo=FALSE}
# library(patchwork)
# 
# combined_plot <- ((p1 | p2) / (p3 | p4)) +
#   plot_layout(ncol = 1) +
#   plot_annotation(
#     tag_levels = 'a',
#     tag_suffix = ") ",
#     theme = theme(
#       plot.margin = margin(t = 10, r = 10, b = 10, l = 10)
#     )
#   ) +
#   draw_label("Generation", size = 18, x = 0.5, y = 0, hjust = 0.5) +
#   draw_label("Phenotype", size = 18, x = 0, y = 0.5, vjust = 0.5, angle = 90)
# 
# combined_plot

```

```{r,echo=FALSE}
# mygrid <- plot_grid(p1, p2, p3, p4, labels = "AUTO", ncol = 2, align = "hv") +
#   theme(plot.margin = margin(t = 10, r = 10, b = 10, l = 10)) +
#   draw_label("Generation", size = 18, x = 0.5, y = 0, hjust = 0.5, fontface = "bold") +
#   draw_label("Phenotype", size = 18, x = -0.01, y = 0.5, vjust = 0.5, angle = 90, fontface = "bold")
# mygrid

```

```{r, echo=FALSE}
# file <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFSGen.dir/MeanPhenotypes1_n100_H0.1SD2.csv") %>% 
#   filter(Generation < 200)
# 
# Optimum = file$Optimum
# 
# ggplot(file) + 
#   geom_line(aes(Generation, Optimum)) +
#   geom_hline(yintercept = mean(file$Phenotype), color = "darkred")+
#   annotate("text", x = 100, y = mean(file$Phenotype), label = "Mean Phenotype", size = 3, vjust = -1.5, col = "darkred")+
#   #annotate("text", x = 38, y = 105, label = "Optimum", size = 3, vjust = -1.5, col = "black")+
#   labs(x = NULL, y = NULL)+ #title = "Sinusoidal IV Periods",
#   mytheme()

```
