---
title: "Phenotype plots"
format: html
author: "Esdras T"
editor: visual
---

## Source Code

```{r, message=FALSE}
rm(list = ls())
source('~/YeastProj.dir/evogen-sims/ET_Yeast/Writing1.dir/Code.dir/PhenotypePlotCode.R')
```

### Neutral selection

```{r, message=FALSE}
dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/NS.dir/"
pattern <- "^MeanPhenotypes(1|2|3)_n\\d+_H0.1_*" #|10|15|20|30
# "^MeanPhenotypes15\\D" #(\\D|$).    (1|2|3|10|13|17|21)_n
result <- process_files(dirpath, pattern, "loci")
plots <- result$plots
plots

```

### NS, CS, and SinFS single locus

```{r, message=FALSE}
pheno1 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/NS.dir/MeanPhenotypes1_n1_H0.8.csv")
p1 <- pheno1 %>% ggplot(aes(Generation, Phenotype))+
  geom_line()

pheno2 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/CS.dir/MeanPhenotypes1_n1_H0.8SD2.csv")
p2 <- pheno2 %>% ggplot(aes(Generation, Phenotype))+
  geom_line()

pheno3 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFSGen.dir/MeanPhenotypes1_n1_H0.8SD2.csv")
p3 <- pheno3 %>% ggplot(aes(Generation, Phenotype))+
  geom_line()

p1/p2/p3
```

### Constant selection

```{r, message=FALSE}
dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/CS.dir/"
pattern <- "^MeanPhenotypes(1|2|3)_n*" #|10|15|20|30
# "^MeanPhenotypes15\\D" #(\\D|$).    (1|2|3|10|13|17|21)_n
result <- process_files(dirpath, pattern, "loci")
#combined_data <- result$combined_data
#plots <- result$plots
result$plots

```

### Fluctuating Linear

```{r, message=FALSE}
dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/"
pattern <- "^MeanPhenotypes(1|2|3|10|15|20|30)_n*"
result <- process_files(dirpath, pattern, "loci_gen")
#combined_data <- result$combined_data
#plots <- result$plots

result$plots

```

```{r, message=FALSE}
pheno1 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes10_n1_H0.1SD1Gen10.csv")
p1 <- pheno1 %>% ggplot(aes(Generation, Phenotype))+
  geom_line()

pheno2 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes10_n1_H0.5SD1Gen10.csv")
p2 <- pheno2 %>% ggplot(aes(Generation, Phenotype))+
  geom_line()

pheno3 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes10_n1_H0.8SD1Gen10.csv")
p3 <- pheno3 %>% ggplot(aes(Generation, Phenotype))+
  geom_line()

p1/p2/p3
```

```{r, message=FALSE}
geno1 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/genome10_n10_H0.1SD4Gen10.csv")
ggplotly(geno1 %>% ggplot(aes(Generation, Frequency, color = interaction(Position,Effect), group = interaction(Position,Effect), linetypes = interaction(Position,Effect)))+
  geom_line())
```

### Fluctuating Sinusoidal I

```{r, message=FALSE}
dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFS.dir/"
pattern <- "^MeanPhenotypes(1|2|3|10|15|20|30)_n*"
result <- process_files(dirpath, pattern, "loci_gen")
#combined_data <- result$combined_data
#plots <- result$plots
result$plots


```

### Fluctuating Sinusoidal II

```{r, message=FALSE}
dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFSGen.dir/" 
pattern <- "^MeanPhenotypes(1|2|3|10|15|20|30)_n*" 
result <- process_files(dirpath, pattern, "loci") 
#combined_data <- result$combined_data 
#plots <- result$plots 
result$plots

```

```{r}
fike1 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes1_n1_H0.1SD1Gen10.csv") %>% 
  mutate(Phenotype1 = Phenotype) %>% 
  select(Generation, Phenotype1)
fike2 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes1_n10_H0.1SD1Gen10.csv") %>% 
  mutate(Phenotype2 = Phenotype) %>% 
  select(Generation, Phenotype2)
fike3 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes1_n70_H0.1SD1Gen10.csv") %>% 
  mutate(Phenotype3 = Phenotype) %>% 
  select(Generation, Phenotype3)
fike4 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes1_n100_H0.1SD1Gen10.csv") %>% 
  mutate(Phenotype4 = Phenotype) %>% 
  select(Generation, Phenotype4)
fike5 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes1_n300_H0.1SD1Gen10.csv") %>% 
  mutate(Phenotype5 = Phenotype) %>% 
  select(Generation, Phenotype5)

fike %>% 
  filter(Generation>=1000) %>% 
  ggplot(aes(Generation, Phenotype))+
  geom_line()
```

```{r, echo=FALSE, results='hide'}
library(dplyr)

# Define a function to read and process the data
read_and_process <- function(file_path, phenotype_name) {
  read.csv(file_path) %>%
    mutate({{phenotype_name}} := Phenotype) %>%
    select(Generation, {{phenotype_name}})
}

# Use the function to read and process each file
file1 <- read_and_process("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes1_n1_H0.1SD1Gen10.csv", "Phenotype1")
file2 <- read_and_process("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes1_n10_H0.1SD1Gen10.csv", "Phenotype2")
file3 <- read_and_process("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes1_n70_H0.1SD1Gen10.csv", "Phenotype3")
file4 <- read_and_process("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes1_n100_H0.1SD1Gen10.csv", "Phenotype4")
file5 <- read_and_process("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/MeanPhenotypes1_n300_H0.1SD1Gen10.csv", "Phenotype5")

# Join all data frames together
df <- full_join(file1, file2, by = "Generation") %>%
  full_join(file3, by = "Generation") %>%
  full_join(file4, by = "Generation") %>%
  full_join(file5, by = "Generation")

```

```{r, echo=FALSE,results='hide'}
# Calculate covariance matrix
cov_mat <- cov(df[-1])

# # Get upper triangle of the covariance matrix
# upper_tri <- cov_mat[upper.tri(cov_mat)]
# 
# # Print the upper triangle
# print(upper_tri)

cov_mat[lower.tri(cov_mat)] <- NA

# Print the modified covariance matrix
print(cov_mat)

```

```{r, echo=FALSE, results='hide'}
var(df[-1])
```

```{r}
fike <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFSGen.dir/MeanPhenotypes1_n300_H0.1SD1.csv")

P1 <- fike %>% 
  filter(Generation>=1000) %>% 
  ggplot(aes(Generation, Phenotype))+
  geom_line()
```

```{r}
fike <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/CS.dir/MeanPhenotypes1_n300_H0.1SD1.csv")

P2 <- fike %>% 
  filter(Generation>=1000) %>% 
  ggplot(aes(Generation, Phenotype))+
  geom_line()
```

```{r}
P2/P1
```

```{r}
fake <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFSGen.dir/MeanPhenotypes1_n10_H0.1SD4.csv")

PO <- fake %>% 
  filter(Generation>=1000) %>% 
  ggplot(aes(Generation, Phenotype))+
  geom_line()
```

```{r}
fake <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/CS.dir/MeanPhenotypes1_n10_H0.1SD4.csv")

PP <- fake %>% 
  filter(Generation>=1000) %>% 
  ggplot(aes(Generation, Phenotype))+
  geom_line()
```

```{r}
PP/PO
```

```{r}
PP
```
