---
title: "Publication_Figures"
author: "ET"
format: html
editor: visual
---

## Allele Frequency

```{r}
############ Libraries and theme function ########

library(tidyverse)
library(stringr)
library(plotly)
library(patchwork)
library(cowplot)
library(purrr)
library(doParallel)
theme_set(theme_cowplot())
mytheme <- function(){
  theme(axis.title = element_text(face = "bold"),
        axis.text = element_text(face = "italic"),
        plot.title = element_text(hjust = 0.5),
        legend.position = "none")
}
```

```{r}
### Function for allele frequency

#################### Data Processing and plotting ###############

# The first part deals with constant and sinusoidal II
process_files <- function(dirpath, pattern, plot_type) {
  files <- list.files(dirpath, pattern, full.names = TRUE)

  dataframes <- list()
  for(file in files){
    replicate_id <- as.numeric(str_extract(file, "(?<=genome)\\d+"))
    herit <- as.numeric(str_extract(file, "(?<=H)0\\.\\d+"))
    loci <- as.numeric(str_extract(file, "(?<=_n)\\d+"))
    sd <- as.numeric(str_extract(file, "(?<=SD)\\d+"))
    gen <- as.numeric(str_extract(file, "(?<=Gen)\\d+"))

    data <- read.csv(file, header = TRUE) %>%
      select(Generation, Position, Frequency, Effect) %>%
      group_by(Position) %>%
      mutate(Position = factor(Position),
             replicate = replicate_id,
             herit = herit,
             loci = loci,
             sd = sd,
             initFreq = Frequency[Generation == 1],
             h2_sd = paste("h2 = ", herit," ", "sd = ", sd, sep = ""),
             postion_effect_init = paste("position = ", Position," ",
                                         "Effect = ", round(Effect, 2)," ", 
                                         "Initial Freq = ", 
                                         round(initFreq, 2)," ",
                                         "repl = ", " ",replicate, sep = ""))


    # argument for linear and sinusoidal I selections

    if(!is.na(gen)) {
      data$gen <- rep(gen, nrow(data))
    }

    dataframes[[file]] <- data
  }
  combined_data <- bind_rows(dataframes) %>%
    mutate(h2_sd = paste("h2 = ", herit," ", "sd = ", sd, sep = ""),
           loci_gen = paste("loci = ", loci," ", "gen = ", gen, sep = ""))

  # plots for either linear or sinusoidal selections

  plots <- list()
  if (plot_type == "loci_gen") {
    loci_gens <- unique(combined_data$loci_gen)
    for(loci_geni in loci_gens){
      locus_data <- combined_data %>%
        filter(loci_gen == loci_geni)
      
      p <- locus_data %>%
        ggplot(aes(Generation, Frequency, group = postion_effect_init,
                   color = postion_effect_init))+#ostion_effect_init
        geom_line(linewidth = 0.2)+
        facet_wrap(~h2_sd, ncol = 4)+
        ylim(min = 0, max = 1)+
        theme_bw()+
        theme(legend.position = "none")
      
      plots[[loci_geni]] <- ggplotly(p) #ggplotly
    }

    # plots for constant or sinusoidal II selections

  } else if (plot_type == "loci") {
    loci <- unique(combined_data$loci)
    for(locus in loci){
      locus_data <- combined_data %>%
        filter(loci == locus)#,
               #Generation %% (gen+1) == 0,
               #Effect > 1.5)

      # Select 10 random positions
      #selected_positions <- sample(locus_data$Position,
      #size = min(10, nrow(locus_data)), replace = F)
      # Filter the data for the selected positions
      #locus_data <- locus_data %>%
        #filter(Position %in% selected_positions)
      
      p <- locus_data %>%
        ggplot(aes(Generation, Frequency, group = postion_effect_init, #postion_effect_init 
                   color = postion_effect_init))+
        geom_line(linewidth = 0.2)+
        facet_wrap(~h2_sd, ncol = 4)+
        ylim(min = 0, max = 1)+
        theme_bw()#+
        #theme(legend.position = "none")
      plots[[locus]] <- ggplotly(p) #ggplotly
    }
  }

  return(list(combined_data = combined_data, plots = plots))
}

```

### Figure 1: Monogenic Two-Season

### Figure 2: Models Comparison

```{r}
#dirpath <- "~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/"
mono1 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/genome1_n10_H0.1SD2Gen10.csv")
mono2 <-  read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFS.dir/genome1_n10_H0.1SD2Gen10.csv")
mono3 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFSGen.dir/genome1_n10_H0.1SD2.csv")
```

```{r, warning=FALSE, fig.width = 16, fig.height = 8}
# Add a column to distinguish the datasets
geno_file <- mono1 %>% mutate(Selection = "Instantaneous Model")
geno_file2 <- mono2 %>% mutate(Selection = "Gradual 2-Seasons Model")
geno_file3 <- mono3 %>% mutate(Selection = "Gradual 4-Seasons Model")

# Combine the datasets
Genome_dataset <- rbind(geno_file, 
                        geno_file2, geno_file3) %>% 
  mutate(Selection = fct_relevel(Selection, 
                                 "Instantaneous Model", 
                                 "Gradual 2-Seasons Model", 
                                 "Gradual 4-Seasons Model"))

# Create the plot
freqplot <- Genome_dataset %>% 
  filter(Generation <= 500) %>% 
  ggplot(aes(x = Generation, y = Frequency, color = factor(Position))) +
  geom_line(linewidth = 0.2) +
  facet_wrap(Selection~.) +
  theme_cowplot()+
  theme(legend.position = "none",
        axis.text = element_text( size = 12, face = "bold"),
        axis.line = element_line(size = 1),
        axis.title = element_text( size = 12, face = "bold"))

freqplot
```

### Neutral vs Gradual 4 seasons

```{r}
neutr1 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/NS.dir/genome1_n10_H0.5.csv")
mono3 <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/SinFSGen.dir/genome1_n10_H0.5SD2.csv")
```

```{r, warning=FALSE, fig.width = 16, fig.height = 8}
# Add a column to distinguish the datasets
geno_file <- neutr1 %>% mutate(Selection = "Neutral Model")
geno_file3 <- mono3 %>% mutate(Selection = "Gradual 4-Seasons Model")

# Combine the datasets
Genome_dataset <- rbind(geno_file, geno_file3) %>% 
  mutate(Selection = fct_relevel(Selection, 
                                 "Neutral Model",  
                                 "Gradual 4-Seasons Model"))

# Create the plot
freqplot <- Genome_dataset %>% ggplot(aes(x = Generation, y = Frequency, color = factor(Position))) +
  geom_line(linewidth = 0.2) +
  facet_wrap(Selection~.) +
  theme_cowplot()+
  theme(legend.position = "none",
        axis.text = element_text( size = 12, face = "bold"),
        axis.line = element_line(size = 1),
        axis.title = element_text( size = 12, face = "bold"))

freqplot
```

### Genome Size

```{r}
Mono <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/genome1_n1_H0.1SD3Gen10.csv")
Oligo <- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/genome1_n10_H0.1SD3Gen10.csv")
Poly<- read.csv("~/YeastProj.dir/evogen-sims/ET_Yeast/output.dir/Selection_Models/WF.dir/LinFS.dir/genome1_n100_H0.1SD3Gen10.csv")
```

```{r, warning=FALSE, fig.width = 16, fig.height = 8}
# Add a column to distinguish the datasets
geno_file <- Mono %>% mutate(Selection = "Monogenic")
geno_file2 <- Oligo %>% mutate(Selection = "Oligogenic")
geno_file3 <- Poly %>% mutate(Selection = "Polygenic")

# Combine the datasets
Genome_dataset <- rbind(geno_file, geno_file2, geno_file3) %>% 
  mutate(Selection = fct_relevel(Selection, 
                                 "Monogenic",  
                                 "Oligogenic", 
                                 "Polygenic"))

# Create the plot
freqplot <- Genome_dataset %>% 
  filter(Generation <= 500) %>% 
  ggplot(aes(x = Generation, y = Frequency, color = factor(Position))) +
  geom_line(linewidth = 0.2) +
  facet_grid(Selection~.) +
  theme_cowplot()+
  theme(legend.position = "none",
        axis.text = element_text( size = 12, face = "bold"),
        axis.line = element_line(size = 1),
        axis.title = element_text( size = 12, face = "bold"))

freqplot
```
