---
title: "Fitness_Pheno"
format: html
---

## Set up

```{r}
set.seed(2361522)
library(dplyr)
library(cowplot)
theme_set(theme_cowplot())

```

## Phenotypes with scaling

To explore whether the number of loci produces a different distribution of phenotypes, we will make 100 sets of 10,000 phenotypes for each number of loci and look at these distributions. The fitness totally dependent on the phenotype so we don't have to look at that separately. 


```{r}
rm(list = ls())
niter <- 500

nlocis <- c(1, 10, 100,1000)
ninds <- 10000
h2s <- c(0.1,0.5,0.9)

pp <- crossing(h2s, nlocis)

pp.out <- vector(mode = "list", length = nrow(pp))

for(kk in 1:nrow(pp))
{
  
  nloci <- pp$nlocis[kk]
  h2 <- pp$h2s[kk]
  phen_out <- matrix(NA,nrow=ninds,ncol=niter)
    
  for (ii in 1:niter) {
    effects <- rexp(nloci)
    markers <- runif(nloci, 0, 1) #Probability of carrying a given allele 
    additive <- numeric(length = ninds)
    
    for (ind in 1:ninds) {
      geno <- rbinom(nloci, 1, markers)
      effs <- geno*effects
      additive[ind] <- sum(effs)
    }
    V_A <- (1/3)*nloci
    #V_E <- (V_A/h2)- V_A
    V_E <- (V_A - h2 * V_A) / h2
    env <- rnorm(ninds, 0.0, sqrt(V_E))
    
    mup <- 0.5*nloci
    sdp <- sqrt(((1/3)*nloci)/h2)

    df <- tibble(phenotypes = additive + env)
    df$phenotypes_sc <- (df$phenotypes - mup)/sdp
    phen_out[,ii] <- df$phenotypes_sc
    
  }
  pp.out[[kk]] <- phen_out
  
}

```



## Plot the results


```{r}
mm.all <- tibble(rep = character(length = 0),
                 value = numeric(length = 0),
                 nloci = numeric(length = 0),
                 h2 <- numeric(length = 0))

for(kk in 1:nrow(pp))
{
mm <- as_tibble(pp.out[[kk]]) |>
  pivot_longer(everything(),names_to = "rep")
mm$nloci <- pp$nlocis[kk]
mm$h2 <- pp$h2s[kk]
mm.all <- rbind(mm.all, mm)
}



mm.all$rep_code <- paste0(mm.all$nloci,"_", mm.all$rep,"_",mm.all$h2)
mm.all$nlociF <- factor(mm.all$nloci)
mm.all$h2F <- factor(mm.all$h2)

mm.all |>
  ggplot(aes(value, color = h2F, group = rep_code)) +
  geom_density(size = 0.1) + 
  facet_grid(nlociF~.)

```

```{r}
mm.all |> filter(h2F == "0.1") %>% 
  ggplot(aes(value, color = h2F, group = rep_code)) +
  geom_density(size = 0.1) + 
  facet_grid(nlociF~., scales = "free_x")
```

```{r}

```

